// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: savourrpc/airdrop.proto

package airdrop

import (
	common "github.com/cornerstone-labs/acorus/rpc/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DppLinkPointsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConsumerToken string `protobuf:"bytes,1,opt,name=consumer_token,json=consumerToken,proto3" json:"consumer_token,omitempty"`
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Address       string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *DppLinkPointsReq) Reset() {
	*x = DppLinkPointsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savourrpc_airdrop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DppLinkPointsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DppLinkPointsReq) ProtoMessage() {}

func (x *DppLinkPointsReq) ProtoReflect() protoreflect.Message {
	mi := &file_savourrpc_airdrop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DppLinkPointsReq.ProtoReflect.Descriptor instead.
func (*DppLinkPointsReq) Descriptor() ([]byte, []int) {
	return file_savourrpc_airdrop_proto_rawDescGZIP(), []int{0}
}

func (x *DppLinkPointsReq) GetConsumerToken() string {
	if x != nil {
		return x.ConsumerToken
	}
	return ""
}

func (x *DppLinkPointsReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DppLinkPointsReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DppLinkPointsRep struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code common.ReturnCode `protobuf:"varint,1,opt,name=code,proto3,enum=savourrpc.ReturnCode" json:"code,omitempty"`
	Msg  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DppLinkPointsRep) Reset() {
	*x = DppLinkPointsRep{}
	if protoimpl.UnsafeEnabled {
		mi := &file_savourrpc_airdrop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DppLinkPointsRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DppLinkPointsRep) ProtoMessage() {}

func (x *DppLinkPointsRep) ProtoReflect() protoreflect.Message {
	mi := &file_savourrpc_airdrop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DppLinkPointsRep.ProtoReflect.Descriptor instead.
func (*DppLinkPointsRep) Descriptor() ([]byte, []int) {
	return file_savourrpc_airdrop_proto_rawDescGZIP(), []int{1}
}

func (x *DppLinkPointsRep) GetCode() common.ReturnCode {
	if x != nil {
		return x.Code
	}
	return common.ReturnCode(0)
}

func (x *DppLinkPointsRep) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_savourrpc_airdrop_proto protoreflect.FileDescriptor

var file_savourrpc_airdrop_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x69, 0x72, 0x64,
	0x72, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x61, 0x76, 0x6f, 0x75,
	0x72, 0x72, 0x70, 0x63, 0x2e, 0x61, 0x69, 0x72, 0x64, 0x72, 0x6f, 0x70, 0x1a, 0x16, 0x73, 0x61,
	0x76, 0x6f, 0x75, 0x72, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x10, 0x44, 0x70, 0x70, 0x4c, 0x69, 0x6e, 0x6b, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4f, 0x0a,
	0x10, 0x44, 0x70, 0x70, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x70, 0x12, 0x29, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x73, 0x61, 0x76, 0x6f, 0x75, 0x72, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x74, 0x75,
	0x72, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x73,
	0x0a, 0x0e, 0x41, 0x69, 0x72, 0x64, 0x72, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x61, 0x0a, 0x13, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x44, 0x70, 0x70, 0x4c, 0x69, 0x6e,
	0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x23, 0x2e, 0x73, 0x61, 0x76, 0x6f, 0x75, 0x72,
	0x72, 0x70, 0x63, 0x2e, 0x61, 0x69, 0x72, 0x64, 0x72, 0x6f, 0x70, 0x2e, 0x44, 0x70, 0x70, 0x4c,
	0x69, 0x6e, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x73,
	0x61, 0x76, 0x6f, 0x75, 0x72, 0x72, 0x70, 0x63, 0x2e, 0x61, 0x69, 0x72, 0x64, 0x72, 0x6f, 0x70,
	0x2e, 0x44, 0x70, 0x70, 0x4c, 0x69, 0x6e, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x70, 0x22, 0x00, 0x42, 0x27, 0x0a, 0x14, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x73, 0x61, 0x76,
	0x6f, 0x75, 0x72, 0x2e, 0x61, 0x69, 0x72, 0x64, 0x72, 0x6f, 0x70, 0x5a, 0x0f, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x69, 0x72, 0x64, 0x72, 0x6f, 0x70, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_savourrpc_airdrop_proto_rawDescOnce sync.Once
	file_savourrpc_airdrop_proto_rawDescData = file_savourrpc_airdrop_proto_rawDesc
)

func file_savourrpc_airdrop_proto_rawDescGZIP() []byte {
	file_savourrpc_airdrop_proto_rawDescOnce.Do(func() {
		file_savourrpc_airdrop_proto_rawDescData = protoimpl.X.CompressGZIP(file_savourrpc_airdrop_proto_rawDescData)
	})
	return file_savourrpc_airdrop_proto_rawDescData
}

var file_savourrpc_airdrop_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_savourrpc_airdrop_proto_goTypes = []interface{}{
	(*DppLinkPointsReq)(nil), // 0: savourrpc.airdrop.DppLinkPointsReq
	(*DppLinkPointsRep)(nil), // 1: savourrpc.airdrop.DppLinkPointsRep
	(common.ReturnCode)(0),   // 2: savourrpc.ReturnCode
}
var file_savourrpc_airdrop_proto_depIdxs = []int32{
	2, // 0: savourrpc.airdrop.DppLinkPointsRep.code:type_name -> savourrpc.ReturnCode
	0, // 1: savourrpc.airdrop.AirdropService.submitDppLinkPoints:input_type -> savourrpc.airdrop.DppLinkPointsReq
	1, // 2: savourrpc.airdrop.AirdropService.submitDppLinkPoints:output_type -> savourrpc.airdrop.DppLinkPointsRep
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_savourrpc_airdrop_proto_init() }
func file_savourrpc_airdrop_proto_init() {
	if File_savourrpc_airdrop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_savourrpc_airdrop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DppLinkPointsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_savourrpc_airdrop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DppLinkPointsRep); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_savourrpc_airdrop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_savourrpc_airdrop_proto_goTypes,
		DependencyIndexes: file_savourrpc_airdrop_proto_depIdxs,
		MessageInfos:      file_savourrpc_airdrop_proto_msgTypes,
	}.Build()
	File_savourrpc_airdrop_proto = out.File
	file_savourrpc_airdrop_proto_rawDesc = nil
	file_savourrpc_airdrop_proto_goTypes = nil
	file_savourrpc_airdrop_proto_depIdxs = nil
}
